2021-07-22 14:07:27.146 [error] <0.282.0>@gen_server:call gen_server 'Elixir.ChatExampleElixir.Writer' terminated with reason: no such process or port in call to gen_server:call(<0.296.0>, {call,{'basic.publish',0,<<"common-room">>,<<>>,false,false},{amqp_msg,{'P_basic',undefined,undefined,...},...},...}, 60000) in gen_server:call/3 line 246
2021-07-22 14:07:27.157 [error] <0.282.0>@gen_server:call CRASH REPORT Process 'Elixir.ChatExampleElixir.Writer' with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.296.0>, {call,{'basic.publish',0,<<"common-room">>,<<>>,false,false},{amqp_msg,{'P_basic',undefined,undefined,...},...},...}, 60000) in gen_server:call/3 line 246
2021-07-22 14:07:27.157 [error] <0.281.0>@gen_server:call Supervisor 'Elixir.ChatExampleElixir.Sup' had child 'Elixir.ChatExampleElixir.Writer' started with 'Elixir.ChatExampleElixir.Writer':start_link([]) at <0.282.0> exit with reason no such process or port in call to gen_server:call(<0.296.0>, {call,{'basic.publish',0,<<"common-room">>,<<>>,false,false},{amqp_msg,{'P_basic',undefined,undefined,...},...},...}, 60000) in context child_terminated
2021-07-22 14:08:48.224 [error] <0.282.0>@gen_server:call gen_server 'Elixir.ChatExampleElixir.Writer' terminated with reason: no such process or port in call to gen_server:call(<0.296.0>, {call,{'basic.publish',0,<<"common-room">>,<<>>,false,false},{amqp_msg,{'P_basic',undefined,undefined,...},...},...}, 60000) in gen_server:call/3 line 246
2021-07-22 14:08:48.233 [error] <0.282.0>@gen_server:call CRASH REPORT Process 'Elixir.ChatExampleElixir.Writer' with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.296.0>, {call,{'basic.publish',0,<<"common-room">>,<<>>,false,false},{amqp_msg,{'P_basic',undefined,undefined,...},...},...}, 60000) in gen_server:call/3 line 246
2021-07-22 14:08:48.233 [error] <0.281.0>@gen_server:call Supervisor 'Elixir.ChatExampleElixir.Sup' had child 'Elixir.ChatExampleElixir.Writer' started with 'Elixir.ChatExampleElixir.Writer':start_link([]) at <0.282.0> exit with reason no such process or port in call to gen_server:call(<0.296.0>, {call,{'basic.publish',0,<<"common-room">>,<<>>,false,false},{amqp_msg,{'P_basic',undefined,undefined,...},...},...}, 60000) in context child_terminated
2021-07-22 14:10:53.717 [error] <0.313.0>@gen_server:call gen_server 'Elixir.ChatExampleElixir.Writer' terminated with reason: no such process or port in call to gen_server:call(<0.327.0>, {call,{'basic.publish',0,<<"common-room">>,<<>>,false,false},{amqp_msg,{'P_basic',undefined,undefined,...},...},...}, 60000) in gen_server:call/3 line 246
2021-07-22 14:10:53.719 [error] <0.313.0>@gen_server:call CRASH REPORT Process 'Elixir.ChatExampleElixir.Writer' with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.327.0>, {call,{'basic.publish',0,<<"common-room">>,<<>>,false,false},{amqp_msg,{'P_basic',undefined,undefined,...},...},...}, 60000) in gen_server:call/3 line 246
2021-07-22 14:10:53.720 [error] <0.312.0>@gen_server:call Supervisor 'Elixir.ChatExampleElixir.Sup' had child 'Elixir.ChatExampleElixir.Writer' started with 'Elixir.ChatExampleElixir.Writer':start_link([]) at <0.313.0> exit with reason no such process or port in call to gen_server:call(<0.327.0>, {call,{'basic.publish',0,<<"common-room">>,<<>>,false,false},{amqp_msg,{'P_basic',undefined,undefined,...},...},...}, 60000) in context child_terminated
2021-07-22 14:13:05.439 [error] <0.282.0> gen_server 'Elixir.ChatExampleElixir.Writer' terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.Protocol.UndefinedError',description => <<>>,protocol => 'Elixir.String.Chars',value => {'DOWN',#Ref<0.4182278590.1681391618.106330>,process,<0.296.0>,{shutdown,{server_initiated_close,404,<<"NOT_FOUND - no exchange 'common-room' in vhost '/'">>}}}} in 'Elixir.String.Chars':'impl_for!'/1 line 3
2021-07-22 14:13:05.446 [error] <0.282.0> CRASH REPORT Process 'Elixir.ChatExampleElixir.Writer' with 0 neighbours crashed with reason: #{'__exception__' => true,'__struct__' => 'Elixir.Protocol.UndefinedError',description => <<>>,protocol => 'Elixir.String.Chars',value => {'DOWN',#Ref<0.4182278590.1681391618.106330>,process,<0.296.0>,{shutdown,{server_initiated_close,404,<<"NOT_FOUND - no exchange 'common-room' in vhost '/'">>}}}} in 'Elixir.String.Chars':'impl_for!'/1 line 3
2021-07-22 14:13:05.447 [error] <0.281.0> Supervisor 'Elixir.ChatExampleElixir.Sup' had child 'Elixir.ChatExampleElixir.Writer' started with 'Elixir.ChatExampleElixir.Writer':start_link([]) at <0.282.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.Protocol.UndefinedError',description => <<>>,protocol => 'Elixir.String.Chars',value => {'DOWN',#Ref<0.4182278590.1681391618.106330>,process,<0.296.0>,{shutdown,{server_initiated_close,404,<<"NOT_FOUND - no exchange 'common-room' in vhost '/'">>}}}} in 'Elixir.String.Chars':'impl_for!'/1 line 3 in context child_terminated
2021-07-22 14:15:08.048 [error] <0.282.0>@gen_server:call gen_server 'Elixir.ChatExampleElixir.Writer' terminated with reason: no such process or port in call to gen_server:call(<0.296.0>, {call,{'basic.publish',0,<<"common-room">>,<<>>,false,false},{amqp_msg,{'P_basic',undefined,undefined,...},...},...}, 60000) in gen_server:call/3 line 246
2021-07-22 14:15:08.056 [error] <0.282.0>@gen_server:call CRASH REPORT Process 'Elixir.ChatExampleElixir.Writer' with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.296.0>, {call,{'basic.publish',0,<<"common-room">>,<<>>,false,false},{amqp_msg,{'P_basic',undefined,undefined,...},...},...}, 60000) in gen_server:call/3 line 246
2021-07-22 14:15:08.056 [error] <0.281.0>@gen_server:call Supervisor 'Elixir.ChatExampleElixir.Sup' had child 'Elixir.ChatExampleElixir.Writer' started with 'Elixir.ChatExampleElixir.Writer':start_link([]) at <0.282.0> exit with reason no such process or port in call to gen_server:call(<0.296.0>, {call,{'basic.publish',0,<<"common-room">>,<<>>,false,false},{amqp_msg,{'P_basic',undefined,undefined,...},...},...}, 60000) in context child_terminated
2021-07-22 14:28:24.388 [error] <0.298.0> gen_server 'Elixir.ChatExampleElixir.Reader' terminated with reason: bad return value: ok
2021-07-22 14:28:24.395 [error] <0.298.0>@gen_server:handle_common_reply:800 CRASH REPORT Process 'Elixir.ChatExampleElixir.Reader' with 0 neighbours exited with reason: bad return value: ok in gen_server:handle_common_reply/8 line 800
2021-07-22 14:28:24.395 [error] <0.281.0> Supervisor 'Elixir.ChatExampleElixir.Sup' had child 'Elixir.ChatExampleElixir.Reader' started with 'Elixir.ChatExampleElixir.Reader':start_link([]) at <0.298.0> exit with reason bad return value: ok in context child_terminated
2021-07-22 14:28:24.412 [error] <0.313.0> gen_server 'Elixir.ChatExampleElixir.Reader' terminated with reason: bad return value: ok
2021-07-22 14:28:24.412 [error] <0.313.0>@gen_server:handle_common_reply:800 CRASH REPORT Process 'Elixir.ChatExampleElixir.Reader' with 0 neighbours exited with reason: bad return value: ok in gen_server:handle_common_reply/8 line 800
2021-07-22 14:28:24.412 [error] <0.281.0> Supervisor 'Elixir.ChatExampleElixir.Sup' had child 'Elixir.ChatExampleElixir.Reader' started with 'Elixir.ChatExampleElixir.Reader':start_link([]) at <0.313.0> exit with reason bad return value: ok in context child_terminated
2021-07-22 14:28:24.429 [error] <0.328.0> gen_server 'Elixir.ChatExampleElixir.Reader' terminated with reason: bad return value: ok
2021-07-22 14:28:24.429 [error] <0.328.0>@gen_server:handle_common_reply:800 CRASH REPORT Process 'Elixir.ChatExampleElixir.Reader' with 0 neighbours exited with reason: bad return value: ok in gen_server:handle_common_reply/8 line 800
2021-07-22 14:28:24.429 [error] <0.281.0> Supervisor 'Elixir.ChatExampleElixir.Sup' had child 'Elixir.ChatExampleElixir.Reader' started with 'Elixir.ChatExampleElixir.Reader':start_link([]) at <0.328.0> exit with reason bad return value: ok in context child_terminated
2021-07-22 14:28:24.447 [error] <0.342.0> gen_server 'Elixir.ChatExampleElixir.Reader' terminated with reason: bad return value: ok
2021-07-22 14:28:24.447 [error] <0.342.0>@gen_server:handle_common_reply:800 CRASH REPORT Process 'Elixir.ChatExampleElixir.Reader' with 0 neighbours exited with reason: bad return value: ok in gen_server:handle_common_reply/8 line 800
2021-07-22 14:28:24.447 [error] <0.281.0> Supervisor 'Elixir.ChatExampleElixir.Sup' had child 'Elixir.ChatExampleElixir.Reader' started with 'Elixir.ChatExampleElixir.Reader':start_link([]) at <0.342.0> exit with reason bad return value: ok in context child_terminated
2021-07-22 14:28:24.447 [error] <0.281.0> Supervisor 'Elixir.ChatExampleElixir.Sup' had child 'Elixir.ChatExampleElixir.Reader' started with 'Elixir.ChatExampleElixir.Reader':start_link([]) at <0.342.0> exit with reason reached_max_restart_intensity in context shutdown
2021-07-22 14:30:56.688 [error] <0.298.0> gen_server 'Elixir.ChatExampleElixir.Reader' terminated with reason: {'module could not be loaded',[{'Elixir.Maps',get,[[{<<"chat-username">>,longstr,<<"lajos">>},{<<"timestamp_in_ms">>,long,1626956934520}],<<"chat-username">>,<<"UNDEFINED">>],[]},{'Elixir.ChatExampleElixir.Reader',handle_info,2,[{file,"lib/chat_example_elixir/Reader.ex"},{line,49}]},{gen_server,try_dispatch,4,[{file,"gen_server.erl"},{line,680}]},{gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,756}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,226}]}]}
2021-07-22 14:30:56.701 [error] <0.298.0>@Elixir.Maps:get CRASH REPORT Process 'Elixir.ChatExampleElixir.Reader' with 0 neighbours crashed with reason: call to undefined function 'Elixir.Maps':get([{<<"chat-username">>,longstr,<<"lajos">>},{<<"timestamp_in_ms">>,long,1626956934520}], <<"chat-username">>, <<"UNDEFINED">>)
2021-07-22 14:30:56.701 [error] <0.281.0>@Elixir.Maps:get Supervisor 'Elixir.ChatExampleElixir.Sup' had child 'Elixir.ChatExampleElixir.Reader' started with 'Elixir.ChatExampleElixir.Reader':start_link([]) at <0.298.0> exit with reason call to undefined function 'Elixir.Maps':get([{<<"chat-username">>,longstr,<<"lajos">>},{<<"timestamp_in_ms">>,long,1626956934520}], <<"chat-username">>, <<"UNDEFINED">>) in context child_terminated
2021-07-22 14:31:11.203 [error] <0.298.0> gen_server 'Elixir.ChatExampleElixir.Reader' terminated with reason: {{badmap,[{<<"chat-username">>,longstr,<<"lajos">>},{<<"timestamp_in_ms">>,long,1626956934520}]},[{'Elixir.Map',get,[[{<<"chat-username">>,longstr,<<"lajos">>},{<<"timestamp_in_ms">>,long,1626956934520}],<<"chat-username">>,<<"UNDEFINED">>],[{file,"lib/map.ex"},{line,469}]},{'Elixir.ChatExampleElixir.Reader',handle_info,2,[{file,"lib/chat_example_elixir/Reader.ex"},{line,49}]},{gen_server,try_dispatch,4,[{file,"gen_server.erl"},{line,680}]},{gen_server,handle_msg,6,[{file,"gen_server.erl"},{...}]},...]}
2021-07-22 14:31:11.215 [error] <0.298.0> CRASH REPORT Process 'Elixir.ChatExampleElixir.Reader' with 0 neighbours crashed with reason: {{badmap,[{<<"chat-username">>,longstr,<<"lajos">>},{<<"timestamp_in_ms">>,long,1626956934520}]},[{'Elixir.Map',get,[[{<<"chat-username">>,longstr,<<"lajos">>},{<<"timestamp_in_ms">>,long,1626956934520}],<<"chat-username">>,<<"UNDEFINED">>],[{file,"lib/map.ex"},{line,469}]},{'Elixir.ChatExampleElixir.Reader',handle_info,2,[{file,"lib/chat_example_elixir/Reader.ex"},{line,49}]},{gen_server,try_dispatch,4,[{file,"gen_server.erl"},{line,680}]},{gen_server,handle_msg,6,[{file,"gen_server.erl"},{...}]},...]}
2021-07-22 14:31:11.216 [error] <0.281.0> Supervisor 'Elixir.ChatExampleElixir.Sup' had child 'Elixir.ChatExampleElixir.Reader' started with 'Elixir.ChatExampleElixir.Reader':start_link([]) at <0.298.0> exit with reason {{badmap,[{<<"chat-username">>,longstr,<<"lajos">>},{<<"timestamp_in_ms">>,long,1626956934520}]},[{'Elixir.Map',get,[[{<<"chat-username">>,longstr,<<"lajos">>},{<<"timestamp_in_ms">>,long,1626956934520}],<<"chat-username">>,<<"UNDEFINED">>],[{file,"lib/map.ex"},{line,469}]},{'Elixir.ChatExampleElixir.Reader',handle_info,2,[{file,"lib/chat_example_elixir/Reader.ex"},{line,49}]},{gen_server,try_dispatch,4,[{file,"gen_server.erl"},{line,680}]},{gen_server,handle_msg,6,[{file,"gen_server.erl"},{...}]},...]} in context child_terminated
2021-07-22 14:32:53.207 [error] <0.312.0>@Elixir.ChatExampleElixir.Rabbit:extract_header:40 gen_server 'Elixir.ChatExampleElixir.Reader' terminated with reason: call to undefined function lists:keyfind/2 from 'Elixir.ChatExampleElixir.Rabbit':extract_header/3 line 40
2021-07-22 14:32:53.218 [error] <0.312.0>@lists:keyfind CRASH REPORT Process 'Elixir.ChatExampleElixir.Reader' with 0 neighbours crashed with reason: call to undefined function lists:keyfind(<<"chat-username">>, <<"1">>)
2021-07-22 14:32:53.218 [error] <0.295.0>@lists:keyfind Supervisor 'Elixir.ChatExampleElixir.Sup' had child 'Elixir.ChatExampleElixir.Reader' started with 'Elixir.ChatExampleElixir.Reader':start_link([]) at <0.312.0> exit with reason call to undefined function lists:keyfind(<<"chat-username">>, <<"1">>) in context child_terminated
